[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CIMeC"
authors = [{name = "Alberto", email = "alberto.finora@unitn.it"}]
dynamic = ["version", "description"]
